<?php

namespace AppBundle\Repository;

/**
 * FormUploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormUploadRepository extends \Doctrine\ORM\EntityRepository
{
}
